import { route as routeFn } from 'ziggy-js';

declare global {
    var route: typeof routeFn;
}

/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'socialite.filament.admin.oauth.redirect': [
            {
                name: 'provider';
                required: true;
            },
        ];
        'socialite.filament.admin.oauth.callback': [
            {
                name: 'provider';
                required: true;
            },
        ];
        'oauth.callback': [
            {
                name: 'provider';
                required: true;
            },
        ];
        'filament.exports.download': [
            {
                name: 'export';
                required: true;
                binding: 'id';
            },
        ];
        'filament.imports.failed-rows.download': [
            {
                name: 'import';
                required: true;
                binding: 'id';
            },
        ];
        'filament.admin.auth.login': [];
        'filament.admin.auth.password-reset.request': [];
        'filament.admin.auth.password-reset.reset': [];
        'filament.admin.auth.register': [];
        'filament.admin.auth.logout': [];
        'filament.admin.auth.profile': [];
        'filament.admin.pages.dashboard': [];
        'filament.admin.resources.agencies.index': [];
        'filament.admin.resources.agency-campaigns.index': [];
        'filament.admin.resources.campaign-announcements.index': [];
        'filament.admin.resources.campaign-announcements.create': [];
        'filament.admin.resources.campaign-announcements.edit': [
            {
                name: 'record';
                required: true;
            },
        ];
        'filament.admin.resources.campaigns.index': [];
        'filament.admin.resources.campaigns.create': [];
        'filament.admin.resources.campaigns.edit': [
            {
                name: 'record';
                required: true;
            },
        ];
        'filament.admin.resources.companies.index': [];
        'filament.admin.resources.influencer-campaigns.index': [];
        'filament.admin.resources.influencers.index': [];
        'filament.admin.resources.influencers.edit': [
            {
                name: 'record';
                required: true;
            },
        ];
        'filament.admin.resources.products.index': [];
        'filament.admin.resources.products.create': [];
        'filament.admin.resources.products.edit': [
            {
                name: 'record';
                required: true;
            },
        ];
        'filament.admin.resources.users.index': [];
        'filament.admin.resources.users.create': [];
        'filament.admin.resources.users.edit': [
            {
                name: 'record';
                required: true;
            },
        ];
        'boost.browser-logs': [];
        login: [];
        'login.store': [];
        logout: [];
        'password.request': [];
        'password.reset': [
            {
                name: 'token';
                required: true;
            },
        ];
        'password.email': [];
        'password.update': [];
        register: [];
        'register.store': [];
        'verification.notice': [];
        'verification.verify': [
            {
                name: 'id';
                required: true;
            },
            {
                name: 'hash';
                required: true;
            },
        ];
        'verification.send': [];
        'password.confirm': [];
        'password.confirmation': [];
        'password.confirm.store': [];
        'two-factor.login': [];
        'two-factor.login.store': [];
        'two-factor.enable': [];
        'two-factor.confirm': [];
        'two-factor.disable': [];
        'two-factor.qr-code': [];
        'two-factor.secret-key': [];
        'two-factor.recovery-codes': [];
        'two-factor.regenerate-recovery-codes': [];
        'livewire.update': [];
        'livewire.upload-file': [];
        'livewire.preview-file': [
            {
                name: 'filename';
                required: true;
            },
        ];
        'filament-impersonate.leave': [];
        home: [];
        'chats.index': [];
        'chats.store': [];
        'chats.show': [
            {
                name: 'chat';
                required: true;
                binding: 'id';
            },
        ];
        'chats.update': [
            {
                name: 'chat';
                required: true;
                binding: 'id';
            },
        ];
        'chats.delete-image': [
            {
                name: 'chat';
                required: true;
                binding: 'id';
            },
        ];
        'messages.store': [
            {
                name: 'chat';
                required: true;
                binding: 'id';
            },
        ];
        'profile.edit': [];
        'profile.update': [];
        'profile.destroy': [];
        'user-password.edit': [];
        'user-password.update': [];
        'appearance.edit': [];
        'two-factor.show': [];
        'storage.local': [
            {
                name: 'path';
                required: true;
            },
        ];
    }
}
export {};
